### PR TITLE
Reformat code and fix the code

### PR DESCRIPTION
**Pull request by syw123456**
Reformat code and fix the code

### CODE REVIEW

**Comment by syw123456** [comment]
> Reformat Code
Sorry, It's wrong.

**Comment by sodatea** [comment]
The code style change is meaningless and causes potential git blame confusion.

And, all vue core projects uses 2-space indentation, in line with https://github.com/vuejs/eslint-plugin-vue-libs

**Comment by syw123456** [comment]
OK.

**Comment by syw123456** [comment]
> The code style change is meaningless and causes potential git blame confusion.
> 
> And, all vue core projects use 2-space indentation, in line with https://github.com/vuejs/eslint-plugin-vue-libs

But I think the gitignore is not all, so I change it.

**Pull request closed without merging**
